#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

export EDITOR=nvim 

pkill sxhkd
sxhkd &

pkill picom
picom &

pkill mpd
mpd &

xsetroot -cursor_name left_ptr
nitrogen --restore

trackpad-toggle rest

# pick up the number of screens
SCREENS=$(xrandr | grep -w connected | wc -l)
if [[ $SCREENS -eq 1 ]]; then
    # set te number of desktops
    xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-1 --off --output HDMI-2 --off --output DP-1-0 --off --output DP-1-1 --off --output DP-1-2 --off --output DP-1-3 --off
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7
elif [[ $SCREENS -eq 2 ]]; then
    xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1 --off --output HDMI-2 --off --output DP-1-0 --off --output DP-1-1 --off --output DP-1-2 --off --output DP-1-3 --off 
    bspc monitor HDMI-1 -d 1 2 3 4 5 6
    bspc monitor eDP-1 -d 7
fi
nitrogen --restore

pkill polybar
polybar &

change-layout rest

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config window_gap 12
# bspc config border_width 2

# bspc config split_ratio 0.5
# bspc config borderless_monocle true
# bspc config gapless_monocle true

# bspc config pointer_modifier mod1
# bspc config pointer_action1 move
# bspc config pointer_action2 resize_side
# bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
