#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

export EDITOR=nvim 

pkill polybar
polybar &

pkill sxhkd
sxhkd &

pkill picom
picom &

pkill mpd
mpd &

xsetroot -cursor_name left_ptr
nitrogen --restore

trackpad-toggle rest

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config window_gap 12
# bspc config border_width 2

# bspc config split_ratio 0.5
# bspc config borderless_monocle true
# bspc config gapless_monocle true

# bspc config pointer_modifier mod1
# bspc config pointer_action1 move
# bspc config pointer_action2 resize_side
# bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
