#!/bin/bash

#   ▄▄▄██▀▀▀ ▄▄▄       ██▒   █▓ ██▓      ██▓    ▓█████  ██▓    
#     ▒██   ▒████▄    ▓██░   █▒▓██▒     ▓██▒    ▓█   ▀ ▓██▒    
#     ░██   ▒██  ▀█▄   ▓██  █▒░▒██▒     ▒██░    ▒███   ▒██░    
#  ▓██▄██▓  ░██▄▄▄▄██   ▒██ █░░░██░     ▒██░    ▒▓█  ▄ ▒██░    
#   ▓███▒    ▓█   ▓██▒   ▒▀█░  ░██░ ██▓ ░██████▒░▒████▒░██████▒
#   ▒▓▒▒░    ▒▒   ▓▒█░   ░ ▐░  ░▓   ▒▓▒ ░ ▒░▓  ░░░ ▒░ ░░ ▒░▓  ░
#   ▒ ░▒░     ▒   ▒▒ ░   ░ ░░   ▒ ░ ░▒  ░ ░ ▒  ░ ░ ░  ░░ ░ ▒  ░
#   ░ ░ ░     ░   ▒        ░░   ▒ ░ ░     ░ ░      ░     ░ ░   
#   ░   ░         ░  ░      ░   ░    ░      ░  ░   ░  ░    ░  ░
#                          ░         ░                         

down(){
    TODOWN=5
    if [ $1 != "" ]; then
        TODOWN=$1
    fi 
    brightnessctl s "$TODOWN%-" 
}
up(){
    TOADD=5
    if [ $1 != "" ]; then
        TOADD=$1
    fi
    brightnessctl s "+$TOADD%" 
}
print_usage(){
    cat<<EOF
Usage Options:

Syntaxis: [option] <arguments>
        
        -h      --help          Display this text mensaje
        -u      --up            By default up brightness 5
        -d      --down          By default down brightness 5

EOF
}
error(){
    echo 'Usage -h or --help for more information' 
}
if [ "$#" == "0" ]; then
    error
else        
    while getopts "hud-:" flags; do
        case "$flags" in
            -)
                case "${OPTARG}" in
                    help) print_usage; exit 1 ;;
                    up) shift ; up "$1" ;;
                    down) shift; down $1 ;;
                    *) error; exit 1 ;;
                esac
            ;; 
            h) print_usage; exit 1 ;;
            u) shift; up "$1" ;; 
            d) shift; down "$1" ;;
            *) error; exit 1 ;;
        esac
    done
    # Get the percen of brightness
    porcent=$(($(brightnessctl g)*100/$(brightnessctl m)))
    # Set the name of the icon or the path
    icon=(brightness-1 brightness-2 brightness-3 brightness-4 brightness-5 brightness-6 brightness-7)
    # With the past icons you take the one you need with respect to percentage
    iconNum=$(( ((($porcent*(${#icon[@]}-1)/10)+5)/10) ))
    notify-send -i "${icon[$iconNum]}" "Brightnes = $porcent" -a some_volume_notifiers -t 1000 -h int:value:$porcent -h string:synchronous:'$bar' -r 555
fi
